In [3]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_json("countries.json")

In [6]:
df.head(10)

                                           countries
0  {'name': 'Afghanistan', 'code': 'AF', 'capital...
1  {'name': 'Albania', 'code': 'AL', 'capital': '...
2  {'name': 'Algeria', 'code': 'DZ', 'capital': '...
3  {'name': 'Argentina', 'code': 'AR', 'capital':...
4  {'name': 'Australia', 'code': 'AU', 'capital':...
5  {'name': 'Austria', 'code': 'AT', 'capital': '...
6  {'name': 'Belgium', 'code': 'BE', 'capital': '...
7  {'name': 'Brazil', 'code': 'BR', 'capital': 'B...
8  {'name': 'Canada', 'code': 'CA', 'capital': 'O...
9  {'name': 'Chile', 'code': 'CL', 'capital': 'Sa...

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 1 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   countries  51 non-null     object
dtypes: object(1)
memory usage: 540.0+ bytes

In [8]:
df.isnull().mean()*100

countries    0.0
dtype: float64

In [9]:
new_df = df.head(10)

In [11]:
new_df.shape

(10, 1)

In [16]:
df.isnull()

    countries
0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
30      False
31      False
32      False
33      False
34      False
35      False
36      False
37      False
38      False
39      False
40      False
41      False
42      False
43      False
44      False
45      False
46      False
47      False
48      False
49      False
50      False

In [17]:
df.drop_duplicates()

                                            countries
0   {'name': 'Afghanistan', 'code': 'AF', 'capital...
1   {'name': 'Albania', 'code': 'AL', 'capital': '...
2   {'name': 'Algeria', 'code': 'DZ', 'capital': '...
3   {'name': 'Argentina', 'code': 'AR', 'capital':...
4   {'name': 'Australia', 'code': 'AU', 'capital':...
5   {'name': 'Austria', 'code': 'AT', 'capital': '...
6   {'name': 'Belgium', 'code': 'BE', 'capital': '...
7   {'name': 'Brazil', 'code': 'BR', 'capital': 'B...
8   {'name': 'Canada', 'code': 'CA', 'capital': 'O...
9   {'name': 'Chile', 'code': 'CL', 'capital': 'Sa...
10  {'name': 'China', 'code': 'CN', 'capital': 'Be...
11  {'name': 'Colombia', 'code': 'CO', 'capital': ...
12  {'name': 'Czech Republic', 'code': 'CZ', 'capi...
13  {'name': 'Denmark', 'code': 'DK', 'capital': '...
14  {'name': 'Egypt', 'code': 'EG', 'capital': 'Ca...
15  {'name': 'Finland', 'code': 'FI', 'capital': '...
16  {'name': 'France', 'code': 'FR', 'capital': 'P...
17  {'name': 'Germany', 'code': 'DE', 'capital': '...
18  {'name': 'Greece', 'code': 'GR', 'capital': 'A...
19  {'name': 'India', 'code': 'IN', 'capital': 'Ne...
20  {'name': 'Indonesia', 'code': 'ID', 'capital':...
21  {'name': 'Ireland', 'code': 'IE', 'capital': '...
22  {'name': 'Israel', 'code': 'IL', 'capital': 'J...
23  {'name': 'Italy', 'code': 'IT', 'capital': 'Ro...
24  {'name': 'Japan', 'code': 'JP', 'capital': 'To...
25  {'name': 'Kenya', 'code': 'KE', 'capital': 'Na...
26  {'name': 'Malaysia', 'code': 'MY', 'capital': ...
27  {'name': 'Mexico', 'code': 'MX', 'capital': 'M...
28  {'name': 'Netherlands', 'code': 'NL', 'capital...
29  {'name': 'New Zealand', 'code': 'NZ', 'capital...
30  {'name': 'Nigeria', 'code': 'NG', 'capital': '...
31  {'name': 'Norway', 'code': 'NO', 'capital': 'O...
32  {'name': 'Pakistan', 'code': 'PK', 'capital': ...
33  {'name': 'Philippines', 'code': 'PH', 'capital...
34  {'name': 'Poland', 'code': 'PL', 'capital': 'W...
35  {'name': 'Portugal', 'code': 'PT', 'capital': ...
36  {'name': 'Russia', 'code': 'RU', 'capital': 'M...
37  {'name': 'Saudi Arabia', 'code': 'SA', 'capita...
38  {'name': 'Singapore', 'code': 'SG', 'capital':...
39  {'name': 'South Africa', 'code': 'ZA', 'capita...
40  {'name': 'South Korea', 'code': 'KR', 'capital...
41  {'name': 'Spain', 'code': 'ES', 'capital': 'Ma...
42  {'name': 'Sweden', 'code': 'SE', 'capital': 'S...
43  {'name': 'Switzerland', 'code': 'CH', 'capital...
44  {'name': 'Thailand', 'code': 'TH', 'capital': ...
45  {'name': 'Turkey', 'code': 'TR', 'capital': 'A...
46  {'name': 'Ukraine', 'code': 'UA', 'capital': '...
47  {'name': 'United Arab Emirates', 'code': 'AE',...
48  {'name': 'United Kingdom', 'code': 'GB', 'capi...
49  {'name': 'United States', 'code': 'US', 'capit...
50  {'name': 'Vietnam', 'code': 'VN', 'capital': '...

In [ ]:
df.