In [1]:
import  pandas as pd

In [2]:
df = pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")

In [3]:
df.shape

(150, 5)

In [5]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [7]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [8]:
df.head(3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [9]:
df.tail(3)

     sepal_length  sepal_width  petal_length  petal_width    species
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [10]:
df.sample(2)

     sepal_length  sepal_width  petal_length  petal_width    species
124           6.7          3.3           5.7          2.1  virginica
6             4.6          3.4           1.4          0.3     setosa

In [11]:
df.size

750

In [12]:
df["sepal_length"]

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [16]:
df[["sepal_width","sepal_width"]]

     sepal_width  sepal_width
0            3.5          3.5
1            3.0          3.0
2            3.2          3.2
3            3.1          3.1
4            3.6          3.6
..           ...          ...
145          3.0          3.0
146          2.5          2.5
147          3.0          3.0
148          3.4          3.4
149          3.0          3.0

[150 rows x 2 columns]

In [21]:
df.iloc[:3]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [22]:
df.iloc[:-1]

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica

[149 rows x 5 columns]

In [26]:
df.iloc[3:8]

   sepal_length  sepal_width  petal_length  petal_width species
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa

In [29]:
df[::]

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

2. Select rows using .iloc

In [30]:
df.iloc[0]

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object

In [32]:
df.iloc[-1]

sepal_length          5.9
sepal_width           3.0
petal_length          5.1
petal_width           1.8
species         virginica
Name: 149, dtype: object

B. Multiple rows using a list

In [33]:
df.iloc[[0,2]]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [36]:
df.iloc[[3,5,10]]

    sepal_length  sepal_width  petal_length  petal_width species
3            4.6          3.1           1.5          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa

C. Rows using slices

In [37]:
df.iloc[0:2]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [38]:
df.iloc[1:5]

   sepal_length  sepal_width  petal_length  petal_width species
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [39]:
df.iloc[:]

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [40]:
df.iloc[2:]

     sepal_length  sepal_width  petal_length  petal_width    species
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[148 rows x 5 columns]

In [41]:
df.iloc[:3]

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

df.iloc[start:stop:step]

In [43]:
df.iloc[2:80:2]

    sepal_length  sepal_width  petal_length  petal_width     species
2            4.7          3.2           1.3          0.2      setosa
4            5.0          3.6           1.4          0.2      setosa
6            4.6          3.4           1.4          0.3      setosa
8            4.4          2.9           1.4          0.2      setosa
10           5.4          3.7           1.5          0.2      setosa
12           4.8          3.0           1.4          0.1      setosa
14           5.8          4.0           1.2          0.2      setosa
16           5.4          3.9           1.3          0.4      setosa
18           5.7          3.8           1.7          0.3      setosa
20           5.4          3.4           1.7          0.2      setosa
22           4.6          3.6           1.0          0.2      setosa
24           4.8          3.4           1.9          0.2      setosa
26           5.0          3.4           1.6          0.4      setosa
28           5.2          3.4           1.4          0.2      setosa
30           4.8          3.1           1.6          0.2      setosa
32           5.2          4.1           1.5          0.1      setosa
34           4.9          3.1           1.5          0.1      setosa
36           5.5          3.5           1.3          0.2      setosa
38           4.4          3.0           1.3          0.2      setosa
40           5.0          3.5           1.3          0.3      setosa
42           4.4          3.2           1.3          0.2      setosa
44           5.1          3.8           1.9          0.4      setosa
46           5.1          3.8           1.6          0.2      setosa
48           5.3          3.7           1.5          0.2      setosa
50           7.0          3.2           4.7          1.4  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
56           6.3          3.3           4.7          1.6  versicolor
58           6.6          2.9           4.6          1.3  versicolor
60           5.0          2.0           3.5          1.0  versicolor
62           6.0          2.2           4.0          1.0  versicolor
64           5.6          2.9           3.6          1.3  versicolor
66           5.6          3.0           4.5          1.5  versicolor
68           6.2          2.2           4.5          1.5  versicolor
70           5.9          3.2           4.8          1.8  versicolor
72           6.3          2.5           4.9          1.5  versicolor
74           6.4          2.9           4.3          1.3  versicolor
76           6.8          2.8           4.8          1.4  versicolor
78           6.0          2.9           4.5          1.5  versicolor

In [44]:
df.iloc[::3]

     sepal_length  sepal_width  petal_length  petal_width     species
0             5.1          3.5           1.4          0.2      setosa
3             4.6          3.1           1.5          0.2      setosa
6             4.6          3.4           1.4          0.3      setosa
9             4.9          3.1           1.5          0.1      setosa
12            4.8          3.0           1.4          0.1      setosa
15            5.7          4.4           1.5          0.4      setosa
18            5.7          3.8           1.7          0.3      setosa
21            5.1          3.7           1.5          0.4      setosa
24            4.8          3.4           1.9          0.2      setosa
27            5.2          3.5           1.5          0.2      setosa
30            4.8          3.1           1.6          0.2      setosa
33            5.5          4.2           1.4          0.2      setosa
36            5.5          3.5           1.3          0.2      setosa
39            5.1          3.4           1.5          0.2      setosa
42            4.4          3.2           1.3          0.2      setosa
45            4.8          3.0           1.4          0.3      setosa
48            5.3          3.7           1.5          0.2      setosa
51            6.4          3.2           4.5          1.5  versicolor
54            6.5          2.8           4.6          1.5  versicolor
57            4.9          2.4           3.3          1.0  versicolor
60            5.0          2.0           3.5          1.0  versicolor
63            6.1          2.9           4.7          1.4  versicolor
66            5.6          3.0           4.5          1.5  versicolor
69            5.6          2.5           3.9          1.1  versicolor
72            6.3          2.5           4.9          1.5  versicolor
75            6.6          3.0           4.4          1.4  versicolor
78            6.0          2.9           4.5          1.5  versicolor
81            5.5          2.4           3.7          1.0  versicolor
84            5.4          3.0           4.5          1.5  versicolor
87            6.3          2.3           4.4          1.3  versicolor
90            5.5          2.6           4.4          1.2  versicolor
93            5.0          2.3           3.3          1.0  versicolor
96            5.7          2.9           4.2          1.3  versicolor
99            5.7          2.8           4.1          1.3  versicolor
102           7.1          3.0           5.9          2.1   virginica
105           7.6          3.0           6.6          2.1   virginica
108           6.7          2.5           5.8          1.8   virginica
111           6.4          2.7           5.3          1.9   virginica
114           5.8          2.8           5.1          2.4   virginica
117           7.7          3.8           6.7          2.2   virginica
120           6.9          3.2           5.7          2.3   virginica
123           6.3          2.7           4.9          1.8   virginica
126           6.2          2.8           4.8          1.8   virginica
129           7.2          3.0           5.8          1.6   virginica
132           6.4          2.8           5.6          2.2   virginica
135           7.7          3.0           6.1          2.3   virginica
138           6.0          3.0           4.8          1.8   virginica
141           6.9          3.1           5.1          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
147           6.5          3.0           5.2          2.0   virginica

In [47]:
df.iloc[2::2]

     sepal_length  sepal_width  petal_length  petal_width    species
2             4.7          3.2           1.3          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
6             4.6          3.4           1.4          0.3     setosa
8             4.4          2.9           1.4          0.2     setosa
10            5.4          3.7           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
140           6.7          3.1           5.6          2.4  virginica
142           5.8          2.7           5.1          1.9  virginica
144           6.7          3.3           5.7          2.5  virginica
146           6.3          2.5           5.0          1.9  virginica
148           6.2          3.4           5.4          2.3  virginica

[74 rows x 5 columns]

In [48]:
df.iloc[::-1]

     sepal_length  sepal_width  petal_length  petal_width    species
149           5.9          3.0           5.1          1.8  virginica
148           6.2          3.4           5.4          2.3  virginica
147           6.5          3.0           5.2          2.0  virginica
146           6.3          2.5           5.0          1.9  virginica
145           6.7          3.0           5.2          2.3  virginica
..            ...          ...           ...          ...        ...
4             5.0          3.6           1.4          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
0             5.1          3.5           1.4          0.2     setosa

[150 rows x 5 columns]